[workspace]
members = [
    "cli",
    "config",
    "db",
    "web",
    "macros"
]
resolver = "2"
default-members = ["web"]

[workspace.metadata.cargo-autoinherit]
# Skip cargo-autoinherit for these packages
exclude-members = [
    "cargo-autoinherit-test-web"
]
